# Generated by Django 3.2 on 2021-04-29 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_comment_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 14, 6, 38, 442973), verbose_name='date created'),
        ),
    ]
